version: '3.8'

services:
  ms-citas:
    build: .
    networks:
      - cuba-network
    ports:
      - "8081:8080"
    environment:
      - DB_MSSQL_HOST=sqlserver-dev
      - DB_MSSQL_DATABASE=clinic
      - DB_MSSQL_USER=SA
      - DB_MSSQL_PASSWORD=Elalmendro.33

networks:
  cuba-network:
    external: true