version: '3.8'

services:
  ms-citas:
    build: .
    image: ms-citas
    container_name: ms-citas
    ports:
      - "8081:8081"
    environment:
      - DB_MSSQL_HOST=sqlserver-dev
      - DB_MSSQL_DATABASE=clinic
      - DB_MSSQL_USER=SA
      - DB_MSSQL_PASSWORD=Elalmendro.33
    networks:
      cuba-network:
        aliases:
          - ms-citas

networks:
  cuba-network:
    external: true
    name: cuba-network  # Especifica explícitamente el nombre