spring.application.name=ms-citas
server.port=8081
server.servlet.context-path=/api/rest

# Propiedades BBDD

db.mssql.host=localhost\\SQLSERVER
db.mssql.database=clinic
db.mssql.user=anicolcl
db.mssql.password=Elalmendro-3